import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    KEYCLOAK_CLIENT_SECRET: z.string().min(1),
    POSTGRES_URL: z.string().url(),
    REDIS_URL: z.string().url(),
    OPENAI_API_KEY: z.string().min(1),
    GROQ_API_KEY: z.string().min(1),
    PERPLEXITY_API_KEY: z.string().min(1),
    GOOGLE_CLIENT_ID: z.string().min(1),
    GOOGLE_CLIENT_SECRET: z.string().min(1),
    MICROSOFT_CLIENT_ID: z.string().min(1),
    MICROSOFT_CLIENT_SECRET: z.string().min(1),
    NOTION_CLIENT_ID: z.string().min(1),
    NOTION_CLIENT_SECRET: z.string().min(1),
    DODOPAYMENTS_API_KEY: z.string().min(1),
    DODOPAYMENTS_SECRET_KEY: z.string().min(1),
    DODOPAYMENTS_WEBHOOK_SECRET: z.string().min(1),
    RUSTFS_ENDPOINT: z.string().url(),
    RUSTFS_ACCESS_KEY: z.string().min(1),
    RUSTFS_SECRET_KEY: z.string().min(1),
    RUSTFS_BUCKET_NAME: z.string().min(1),
    RUSTFS_REGION: z.string().min(1),
  },
  client: {
    NEXT_PUBLIC_KEYCLOAK_URL: z.string().url(),
    NEXT_PUBLIC_KEYCLOAK_REALM: z.string().min(1),
    NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: z.string().min(1),
    NEXT_PUBLIC_APP_URL: z.string().url(),
  },
  // If you're using Next.js < 13.4.4, you'll need to specify the runtimeEnv manually
  runtimeEnv: {
    NEXT_PUBLIC_KEYCLOAK_URL: process.env.NEXT_PUBLIC_KEYCLOAK_URL,
    NEXT_PUBLIC_KEYCLOAK_REALM: process.env.NEXT_PUBLIC_KEYCLOAK_REALM,
    NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: process.env.NEXT_PUBLIC_KEYCLOAK_CLIENT_ID,
    KEYCLOAK_CLIENT_SECRET: process.env.KEYCLOAK_CLIENT_SECRET,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
    POSTGRES_URL: process.env.POSTGRES_URL,
    REDIS_URL: process.env.REDIS_URL,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY,
    GROQ_API_KEY: process.env.GROQ_API_KEY,
    PERPLEXITY_API_KEY: process.env.PERPLEXITY_API_KEY,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    MICROSOFT_CLIENT_ID: process.env.MICROSOFT_CLIENT_ID,
    MICROSOFT_CLIENT_SECRET: process.env.MICROSOFT_CLIENT_SECRET,
    NOTION_CLIENT_ID: process.env.NOTION_CLIENT_ID,
    NOTION_CLIENT_SECRET: process.env.NOTION_CLIENT_SECRET,
    DODOPAYMENTS_API_KEY: process.env.DODOPAYMENTS_API_KEY,
    DODOPAYMENTS_SECRET_KEY: process.env.DODOPAYMENTS_SECRET_KEY,
    DODOPAYMENTS_WEBHOOK_SECRET: process.env.DODOPAYMENTS_WEBHOOK_SECRET,
    RUSTFS_ENDPOINT: process.env.RUSTFS_ENDPOINT,
    RUSTFS_ACCESS_KEY: process.env.RUSTFS_ACCESS_KEY,
    RUSTFS_SECRET_KEY: process.env.RUSTFS_SECRET_KEY,
    RUSTFS_BUCKET_NAME: process.env.RUSTFS_BUCKET_NAME,
    RUSTFS_REGION: process.env.RUSTFS_REGION,
  },
});
